config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :ads
  root 'ads#index'
end

app/models/ad.rb
class Ad < ActiveRecord::Base
	validates :title, presence: true
	validates :description, length: {minimum: 10}, allow_blank: false
	
	belongs_to :category
	belongs_to :user

	has_attached_file :img_url, styles: { medium: "300x300>", thumb: "90x90#" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :img_url, content_type: /\Aimage\/.*\Z/

 	def self.search(query)
    where("title like ?", "%#{query}%") 
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :ads
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :ads
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  before_action :set_ad, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /ads
  # GET /ads.json
  def index

    @ads = Ad.order("created_at DESC")
    @ads = @ads.joins(:category).where(categories: { name: params[:category] }) if params[:category].present?
    @ads = @ads.search(params[:search]) if params[:search].present?
    @ads = @ads.paginate(page: params[:page], per_page: 10)

  end

  # GET /ads/1
  # GET /ads/1.json
  def show
  end

  # GET /ads/new
  def new
    @ad = current_user.ads.build
  end

  # GET /ads/1/edit
  def edit
  end

  # POST /ads
  # POST /ads.json
  def create
    @ad = current_user.ads.build(ad_params)

    respond_to do |format|
      if @ad.save
        format.html { redirect_to @ad, notice: 'Ad was successfully created.' }
        format.json { render :show, status: :created, location: @ad }
      else
        format.html { render :new }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ads/1
  # PATCH/PUT /ads/1.json
  def update
    respond_to do |format|
      if @ad.update(ad_params)
        format.html { redirect_to @ad, notice: 'Ad was successfully updated.' }
        format.json { render :show, status: :ok, location: @ad }
      else
        format.html { render :edit }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ads/1
  # DELETE /ads/1.json
  def destroy
    @ad.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Ad was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ad
      @ad = Ad.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ad_params
      params.require(:ad).permit(:title, :description, :price, :img_url, :category_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ads/_form.html.erb
<%= simple_form_for(@ad, html: { multipart:true, class: 'form-horizontal'}) do |f| %>
  <%= f.collection_select :category_id, Category.all, :id, :name, {promt: "Choose a category"} %>
  <%= f.input :title, label: "Ad Title" %>
  <%= f.input :description, label: "Ad Description" %>
  <%= f.input :price, label: "Price" %>
  <%= f.file_field :img_url %>
  <%= f.button :submit %>
<% end %>

app/views/ads/edit.html.erb
<h1>Editing Ad</h1>

<%= render 'form' %>

<%= link_to 'Show', @ad %> |
<%= link_to 'Back', ads_path %>

app/views/ads/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<h1>Latest Ads</h1>
	<ul>
    <% @ads.each do |ad| %>
	    <li class="listing">
	    	<div class="col-xs-2">
	    		<%= image_tag ad.img_url.url(:thumb) %>
	    	</div>
	    	<div class="col-xs-8">
	      	<h2><%= link_to ad.title, ad %></h2>
	      </div>
	      <div class="col-xs-2">
	      	<h3><%= number_to_currency(ad.price) %></h3>
	    	</div>
	    	
	    </li>
	  	</br>
    <% end %>
  </ul>
<br>

<%= will_paginate @ads, renderer: BootstrapPagination::Rails %>

app/views/ads/new.html.erb
<h1>New Ad</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/ads/show.html.erb
<p id="notice"><%= notice %></p>


<%= image_tag @ad.img_url.url(:medium) %>

<p>
  <strong>User:</strong> <%= @ad.user.email %>
</p>

<p>
  <strong>Title:</strong>
  <%= @ad.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @ad.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= number_to_currency(@ad.price) %>
</p>

<p>
  <strong>Img url:</strong>
  <%= @ad.img_url %>
</p>

<% if @ad.user == current_user %>
	<%= link_to 'Destroy', @ad, method: :delete, data: { confirm: 'Are you sure?' } %> |
	<%= link_to 'Edit', edit_ad_path(@ad) %> |
<% end %>

<%= link_to 'Back', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Board</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<nav class="navbar navbar-default">
		<div class="container">
			<%= link_to 'Board', root_path, class: "navbar-brand" %>
			<%= link_to 'New Board Ad', new_ad_path, class: "navbar-text navbar-right navbar-link" %>
			<%= link_to 'Sign up', new_user_registration_path, class: "navbar-right navbar-text" %>
			<%= link_to 'Sign in', new_user_session_path, class: "navbar-right navbar-text" %>
		</div>
	</nav>

<div class="container search-container">
	<%= form_tag(ads_path, :method => "get", class: "navbar-form", id: "search-form") do %>
    <div class="input-append search-wrapper">
      <%= text_field_tag :search, params[:search], class: "span2 form-control search-field", placeholder: "Search Ads" %>
      <button class="btn search-btn" type="submit">Search</button>
    </div>
  <% end %>
 </div> 


<div class="container">
<ul class="nav nav-tabs nav-justified">
	<li><%= link_to "All Categories", root_path %></li>
	<% Category.all.each do |category| %>
		<li><%= link_to category.name, ads_path(category: category.name) %></li>
	<% end %>
</ul>

	<p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

	<%= yield %>
</div>
</body>
</html>